QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

TRANSLATIONS += ./VmsTsFile/VmsTranslator_zh_CN.ts\
				./VmsTsFile/VmsTranslator_ESP.ts\
				./VmsTsFile/VmsTranslator_FR.ts\
				./VmsTsFile/VmsTranslator_TH.ts\
				./VmsTsFile/VmsTranslator_DE.ts\
				./VmsTsFile/VmsTranslator_JA.ts\
				./VmsTsFile/VmsTranslator_IT.ts\
				./VmsTsFile/VmsTranslator_AR.ts\
				./VmsTsFile/VmsTranslator_RU.ts\
				./VmsTsFile/VmsTranslator_PT.ts\
				./VmsTsFile/VmsTranslator_VN.ts\
				./VmsTsFile/VmsTranslator_MS.ts\
				./VmsTsFile/VmsTranslator_IN.ts\
				./VmsTsFile/VmsTranslator_KR.ts\
				./VmsTsFile/VmsTranslator_ID.ts\
				./VmsTsFile/VmsTranslator_HE.ts\
				./VmsTsFile/VmsTranslator_PL.ts\
				./VmsTsFile/VmsTranslator_NL.ts\

CODECFORTR = GBK
#//CODECFORTR = UTF-8
#QMAKE_CXXFLAGS += -finput-charset=GBK

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    $$files(../../common/*.cpp, true) \
    $$files(../../commonWidget/*.cpp, true) \
    $$files(../*.cpp, true) \
    $$files(../DataStructure/*.cpp, true) \
    $$files(../Functional/*.cpp, true) \
    $$files(../Public/*.cpp, true)

HEADERS += \
    $$files(../../common/*.h, true) \
    $$files(../../commonWidget/*.h, true) \
    $$files(../*.h, true) \
    $$files(../DataStructure/*.h, true) \
    $$files(../Functional/*.h, true) \
    $$files(../Public/*.h, true)

FORMS += \
    ../Public/AppUpdate.ui \
    ../Public/picturecaptchadilog.ui\

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    ../../common/CMakeLists.txt \
    ../../commonWidget/CMakeLists.txt \
    ../../commonWidget/images/LXAppTitleIcon.png \
    ../../commonWidget/images/LXAppTitleIcon_2.png \
    ../../commonWidget/images/LXSettingHover.png \
    ../../commonWidget/images/LXSettingHover_2.png \
    ../../commonWidget/images/LXhaveLoginStatus.png \
    ../../commonWidget/images/LXhaveLoginStatus_2.png \
    ../../commonWidget/images/MinimizedHover.png \
    ../../commonWidget/images/MinimizedHover_2.png \
    ../../commonWidget/images/MinimizedUnHover.png \
    ../../commonWidget/images/MinimizedUnHover_2.png \
    ../../commonWidget/images/activeInfo.png \
    ../../commonWidget/images/activeInfoHover.png \
    ../../commonWidget/images/activeInfoHover_2.png \
    ../../commonWidget/images/activeInfoNormal.png \
    ../../commonWidget/images/activeInfoNormal_2.png \
    ../../commonWidget/images/activeInfo_2.png \
    ../../commonWidget/images/appTitleIcon.png \
    ../../commonWidget/images/appTitleIcon_2.png \
    ../../commonWidget/images/chevron-down.png \
    ../../commonWidget/images/chevron-down@2x.png \
    ../../commonWidget/images/chevron-up.png \
    ../../commonWidget/images/chevron-up@2x.png \
    ../../commonWidget/images/closeHover.png \
    ../../commonWidget/images/closeHover_2.png \
    ../../commonWidget/images/closeUnHover.png \
    ../../commonWidget/images/closeUnHover_2.png \
    ../../commonWidget/images/createTeam.png \
    ../../commonWidget/images/createTeam2x.png \
    ../../commonWidget/images/haveLoginStatus.png \
    ../../commonWidget/images/haveLoginStatus_2.png \
    ../../commonWidget/images/hoverUnLogin.png \
    ../../commonWidget/images/lianXiangWindowIcon.png \
    ../../commonWidget/images/maxHover.png \
    ../../commonWidget/images/maxHover_2.png \
    ../../commonWidget/images/maxUnHover.png \
    ../../commonWidget/images/maxUnHover_2.png \
    ../../commonWidget/images/minHover.png \
    ../../commonWidget/images/minHover_2.png \
    ../../commonWidget/images/minUnHover.png \
    ../../commonWidget/images/minUnHover_2.png \
    ../../commonWidget/images/noLoginStauts.png \
    ../../commonWidget/images/noLoginStauts_2.png \
    ../../commonWidget/images/owningGroup.png \
    ../../commonWidget/images/owningGroup_2.png \
    ../../commonWidget/images/settingHover.png \
    ../../commonWidget/images/settingHover_2.png \
    ../../commonWidget/images/settingUnHover.png \
    ../../commonWidget/images/settingUnHover_2.png \
    ../../commonWidget/images/teamIco.png \
    ../../commonWidget/images/teamIco2x.png \
    ../../commonWidget/images/teamMembers.png \
    ../../commonWidget/images/teamMembers2x.png \
    ../../commonWidget/images/unLogin.png \
    ../../commonWidget/images/window.rc \
    ../../commonWidget/images/windowIcon.png \
    ../Component/AppSettingPage.qml \
    ../Component/Button/CalendarButton.qml \
    ../Component/Button/CanSelectButton.qml \
    ../Component/Button/DrawButton.qml \
    ../Component/Button/ImageButton.qml \
    ../Component/Button/ShapeRectangle.qml \
    ../Component/Button/ToggleButton.qml \
    ../Component/Button/qmldir \
    ../Component/CardVideo/CardVideoMainPage.qml \
    ../Component/CardVideo/qmldir \
    ../Component/DeviceManager/CloudDeviceMessagePlayBackDialog.qml \
    ../Component/DeviceManager/DetectionAlarm.qml \
    ../Component/DeviceManager/DeviceAPList.qml \
    ../Component/DeviceManager/DeviceBasicInformation.qml \
    ../Component/DeviceManager/DeviceListPage.qml \
    ../Component/DeviceManager/DeviceMamager.qml \
    ../Component/DeviceManager/DeviceManagerPage.qml \
    ../Component/DeviceManager/DeviceSetting.qml \
    ../Component/DeviceManager/DeviceUpdating.qml \
    ../Component/DeviceManager/DialogImg.qml \
    ../Component/DeviceManager/EquipmentMaintenance.qml \
    ../Component/DeviceManager/ImageInformation.qml \
    ../Component/DeviceManager/LanSearchPage.qml \
    ../Component/DeviceManager/MessageBoxShow.qml \
    ../Component/DeviceManager/MessageInfoPage.qml \
    ../Component/DeviceManager/NetworkInformation.qml \
    ../Component/DeviceManager/PowerManagement.qml \
    ../Component/DeviceManager/ReNameDialog.qml \
    ../Component/DeviceManager/TimingFullColor.qml \
    ../Component/DeviceManager/qmldir \
    ../Component/Edit/CustomCalendar.qml \
    ../Component/Edit/CustomCheckBox.qml \
    ../Component/Edit/CustomText.qml \
    ../Component/Edit/LineEdit.qml \
    ../Component/Edit/MessageBox.qml \
    ../Component/Edit/Messagetip.qml \
    ../Component/Edit/qmldir \
    ../Component/Login/ForgetPwdPage.qml \
    ../Component/Login/LoginMainPage.qml \
    ../Component/Login/LoginPage.qml \
    ../Component/Login/ModalPage.qml \
    ../Component/Login/ModalPopup.qml \
    ../Component/Login/RegisterPage.qml \
    ../Component/Login/SafeAuthPage.qml \
    ../Component/Login/VipWebViewManager.qml \
    ../Component/Login/qmldir \
    ../Component/MultipleManagement/AddTeamButton.qml \
    ../Component/MultipleManagement/BatchImportTemplates.qml \
    ../Component/MultipleManagement/BuyFlowRateTips.qml \
    ../Component/MultipleManagement/StoreEquipmentList.qml \
    ../Component/MultipleManagement/createTeam.qml \
    ../Component/MultipleManagement/qmldir \
    ../Component/SystemInfo/ActiveInfoPage.qml \
    ../Component/SystemInfo/qmldir \
    ../Component/TeamManage/AddMemberPopup.qml \
    ../Component/TeamManage/AddSubDepartmentPopup.qml \
    ../Component/TeamManage/AddTeamDialog.qml \
    ../Component/TeamManage/DepartmentList.qml \
    ../Component/TeamManage/DisbandTeamPopup.qml \
    ../Component/TeamManage/EditTeamInfoPopup.qml \
    ../Component/TeamManage/MessagePopup.qml \
    ../Component/TeamManage/Pagination.qml \
    ../Component/TeamManage/TeamDepartmentComboBox.qml \
    ../Component/TeamManage/TeamDepartmentPage.qml \
    ../Component/TeamManage/TeamInfoPage.qml \
    ../Component/TeamManage/TeamManageMainPage.qml \
    ../Component/TeamManage/TeamMemberView.qml \
    ../Component/TeamManage/TeamReviewPage.qml \
    ../Component/TeamManage/TeamReviewPopup.qml \
    ../Component/TeamManage/qmldir \
    ../Component/VideoPage/BuyFlowRateTips.qml \
    ../Component/VideoPage/CardPlayBackPage.qml \
    ../Component/VideoPage/CloudPlayBackPage.qml \
    ../Component/VideoPage/DeleteCloudFileDialog.qml \
    ../Component/VideoPage/DownloadCloudFileDialog.qml \
    ../Component/VideoPage/DynamicPage.qml \
    ../Component/VideoPage/FooterPanel.qml \
    ../Component/VideoPage/LowerImageQualityDownloadVideoDialog.qml \
    ../Component/VideoPage/MainVideoPage.qml \
    ../Component/VideoPage/PlayBackPage.qml \
    ../Component/VideoPage/PtzControlPannel.qml \
    ../Component/VideoPage/TitleBarPanel.qml \
    ../Component/VideoPage/VipNewDeviceTips.qml \
    ../Component/VideoPage/VipRequestErrorTips.qml \
    ../Component/VideoPage/VipTipsMessageBox.qml \
    ../Component/VideoPage/ZoomSlider.qml \
    ../Component/VideoPage/qmldir \
    ../LXicon1.ico \
    ../LianXiangPageStyle/AppSettingPage.css \
    ../LianXiangPageStyle/CardPlayBackPage.css \
    ../LianXiangPageStyle/CardVideoMainPage.css \
    ../LianXiangPageStyle/CloudPlayBackPage.css \
    ../LianXiangPageStyle/CustomCalendar.css \
    ../LianXiangPageStyle/DeleteCloudFileDialog.css \
    ../LianXiangPageStyle/DetectionAlarm.css \
    ../LianXiangPageStyle/DeviceAPList.css \
    ../LianXiangPageStyle/DeviceBasicInformation.css \
    ../LianXiangPageStyle/DeviceListPage.css \
    ../LianXiangPageStyle/DeviceMamager.css \
    ../LianXiangPageStyle/DeviceManagerPage.css \
    ../LianXiangPageStyle/DeviceSetting.css \
    ../LianXiangPageStyle/DownloadCloudFileDialog.css \
    ../LianXiangPageStyle/DynamicPage.css \
    ../LianXiangPageStyle/EquipmentMaintenance.css \
    ../LianXiangPageStyle/FooterPanel.css \
    ../LianXiangPageStyle/ForgetPwdPage.css \
    ../LianXiangPageStyle/ImageInformation.css \
    ../LianXiangPageStyle/LanSearchPage.css \
    ../LianXiangPageStyle/LoginPage.css \
    ../LianXiangPageStyle/LowerImageQualityDownloadVideoDialog.css \
    ../LianXiangPageStyle/MainVideoPage.css \
    ../LianXiangPageStyle/MainWindow.css \
    ../LianXiangPageStyle/MessageBox.css \
    ../LianXiangPageStyle/MessageBoxShow.css \
    ../LianXiangPageStyle/MessageInfoPage.css \
    ../LianXiangPageStyle/NetworkInformation.css \
    ../LianXiangPageStyle/PtzControlPannel.css \
    ../LianXiangPageStyle/ReNameDialog.css \
    ../LianXiangPageStyle/RegisterPage.css \
    ../LianXiangPageStyle/SafeAuthPage.css \
    ../LianXiangPageStyle/StoreEquipmentList.css \
    ../LianXiangPageStyle/TitleBarPanel.css \
    ../LianXiangPageStyle/VipNewDeviceTips.css \
    ../LianXiangPageStyle/VipRequestErrorTips.css \
    ../LianXiangPageStyle/VipTipsMessageBox.css \
    ../LianXiangPageStyle/VipWebViewManager.css \
    ../MainWindow.qml \
    ../QiaoAnPageStyle/AppSettingPage.css \
    ../QiaoAnPageStyle/CardPlayBackPage.css \
    ../QiaoAnPageStyle/CardVideoMainPage.css \
    ../QiaoAnPageStyle/CloudPlayBackPage.css \
    ../QiaoAnPageStyle/CustomCalendar.css \
    ../QiaoAnPageStyle/DeleteCloudFileDialog.css \
    ../QiaoAnPageStyle/DetectionAlarm.css \
    ../QiaoAnPageStyle/DeviceAPList.css \
    ../QiaoAnPageStyle/DeviceBasicInformation.css \
    ../QiaoAnPageStyle/DeviceListPage.css \
    ../QiaoAnPageStyle/DeviceMamager.css \
    ../QiaoAnPageStyle/DeviceManagerPage.css \
    ../QiaoAnPageStyle/DeviceSetting.css \
    ../QiaoAnPageStyle/DownloadCloudFileDialog.css \
    ../QiaoAnPageStyle/DynamicPage.css \
    ../QiaoAnPageStyle/EquipmentMaintenance.css \
    ../QiaoAnPageStyle/FooterPanel.css \
    ../QiaoAnPageStyle/ForgetPwdPage.css \
    ../QiaoAnPageStyle/ImageInformation.css \
    ../QiaoAnPageStyle/LanSearchPage.css \
    ../QiaoAnPageStyle/LoginPage.css \
    ../QiaoAnPageStyle/LowerImageQualityDownloadVideoDialog.css \
    ../QiaoAnPageStyle/MainVideoPage.css \
    ../QiaoAnPageStyle/MainWindow.css \
    ../QiaoAnPageStyle/MessageBox.css \
    ../QiaoAnPageStyle/MessageBoxShow.css \
    ../QiaoAnPageStyle/MessageInfoPage.css \
    ../QiaoAnPageStyle/NetworkInformation.css \
    ../QiaoAnPageStyle/PtzControlPannel.css \
    ../QiaoAnPageStyle/ReNameDialog.css \
    ../QiaoAnPageStyle/RegisterPage.css \
    ../QiaoAnPageStyle/SafeAuthPage.css \
    ../QiaoAnPageStyle/StoreEquipmentList.css \
    ../QiaoAnPageStyle/TitleBarPanel.css \
    ../QiaoAnPageStyle/VipNewDeviceTips.css \
    ../QiaoAnPageStyle/VipRequestErrorTips.css \
    ../QiaoAnPageStyle/VipTipsMessageBox.css \
    ../QiaoAnPageStyle/VipWebViewManager.css \
    ../RCa10468 \
    ../build-VmsTranslate-Desktop_Qt_5_12_12_MSVC2017_32bit-Debug/.qmake.stash \
    ../icon1.ico \
    ../image/app/lianXiangLoading.png \
    ../image/app/lianXiangLoading_2.png \
    ../image/app/loading.png \
    ../image/app/loading_2.png \
    ../image/app/sliderBg1.png \
    ../image/app/sliderBg10.png \
    ../image/app/sliderBg11.png \
    ../image/app/sliderBg1_2.png \
    ../image/app/sliderBg2.png \
    ../image/app/sliderBg3.png \
    ../image/app/sliderBg4.png \
    ../image/app/sliderBg5.png \
    ../image/app/sliderBg6.png \
    ../image/app/sliderBg7.png \
    ../image/app/sliderBg8.png \
    ../image/app/sliderBg9.png \
    ../image/button/LXAddDeviceBtn.png \
    ../image/button/LXAddDeviceBtn_2.png \
    ../image/button/LXCalendarBtnChecked.png \
    ../image/button/LXCalendarBtnChecked_2.png \
    ../image/button/LXCameraControlClose.png \
    ../image/button/LXCameraControlCloseHover.png \
    ../image/button/LXCameraControlCloseHover_2.png \
    ../image/button/LXCameraControlClose_2.png \
    ../image/button/LXCameraControlOpen.png \
    ../image/button/LXCameraControlOpen_2.png \
    ../image/button/LXCloudBatchSelect.png \
    ../image/button/LXCloudBatchSelect_2.png \
    ../image/button/LXCloudChecked.png \
    ../image/button/LXCloudChecked_2.png \
    ../image/button/LXCloudUnChecked.png \
    ../image/button/LXCloudUnChecked_2.png \
    ../image/button/LXComboxExpand.png \
    ../image/button/LXComboxExpand_2.png \
    ../image/button/LXDeviceCheckedStatus.png \
    ../image/button/LXDeviceCheckedStatus_2.png \
    ../image/button/LXDeviceHoverStatus.png \
    ../image/button/LXDeviceHoverStatus_2.png \
    ../image/button/LXDeviceNormal.png \
    ../image/button/LXDeviceNormal_2.png \
    ../image/button/LXInforChecked.png \
    ../image/button/LXInforChecked_2.png \
    ../image/button/LXInforHover.png \
    ../image/button/LXInforHover_2.png \
    ../image/button/LXInforNormal.png \
    ../image/button/LXInforNormal_2.png \
    ../image/button/LXIntercomClose.png \
    ../image/button/LXIntercomCloseHover.png \
    ../image/button/LXIntercomCloseHover_2.png \
    ../image/button/LXIntercomClose_2.png \
    ../image/button/LXIntercomOpenStatus.png \
    ../image/button/LXIntercomOpenStatus_2.png \
    ../image/button/LXMeunCheckedStatus.png \
    ../image/button/LXMeunCheckedStatus_2.png \
    ../image/button/LXPhotoChecked.png \
    ../image/button/LXPhotoChecked_2.png \
    ../image/button/LXPhotoHover.png \
    ../image/button/LXPhotoHover_2.png \
    ../image/button/LXPhotoNormal.png \
    ../image/button/LXPhotoNormal_2.png \
    ../image/button/LXPlayButtonChecked.png \
    ../image/button/LXPlayButtonChecked_2.png \
    ../image/button/LXPlayButtonHover.png \
    ../image/button/LXPlayButtonHover_2.png \
    ../image/button/LXPlayButtonNormal.png \
    ../image/button/LXPlayButtonNormal_2.png \
    ../image/button/LXRealButtonChecked.png \
    ../image/button/LXRealButtonChecked_2.png \
    ../image/button/LXRealButtonHover.png \
    ../image/button/LXRealButtonHover_2.png \
    ../image/button/LXRealButtonNormal.png \
    ../image/button/LXRealButtonNormal_2.png \
    ../image/button/LXRetryPressed.png \
    ../image/button/LXRetryPressed_2.png \
    ../image/button/LXSdCardSelected.png \
    ../image/button/LXSdCardSelected_2.png \
    ../image/button/LXSdCardUnSelected.png \
    ../image/button/LXSdCardUnSelected_2.png \
    ../image/button/LXVideoChecked.png \
    ../image/button/LXVideoChecked_2.png \
    ../image/button/LXVideoHover.png \
    ../image/button/LXVideoHover_2.png \
    ../image/button/LXVideoNormal.png \
    ../image/button/LXVideoNormal_2.png \
    ../image/button/LXVideoReplayChecked.png \
    ../image/button/LXVideoReplayChecked_2.png \
    ../image/button/LXVideoReplayHover.png \
    ../image/button/LXVideoReplayHover_2.png \
    ../image/button/LXVideoReplayNormal.png \
    ../image/button/LXVideoReplayNormal_2.png \
    ../image/button/LXVoiceCheceked.png \
    ../image/button/LXVoiceCheceked_2.png \
    ../image/button/LXVoiceClose.png \
    ../image/button/LXVoiceCloseHover.png \
    ../image/button/LXVoiceCloseHover_2.png \
    ../image/button/LXVoiceClose_2.png \
    ../image/button/LXZoomChecked.png \
    ../image/button/LXZoomHover.png \
    ../image/button/LXZoomNormal.png \
    ../image/button/LXzoolSlider.png \
    ../image/button/LXzoolSlider_2x.png \
    ../image/button/LXzoom.png \
    ../image/button/LXzoom2x.png \
    ../image/button/MaximizedButtonStatus.png \
    ../image/button/RadioButton_checked.png \
    ../image/button/RadioButton_unchecked.png \
    ../image/button/addDeviceBtn.png \
    ../image/button/addDeviceHover.png \
    ../image/button/addDeviceHover_2.png \
    ../image/button/addDeviceNormal.png \
    ../image/button/addDeviceNormal_2.png \
    ../image/button/backButtonChecked.png \
    ../image/button/backButtonChecked_2.png \
    ../image/button/backButtonNormal.png \
    ../image/button/backButtonNormal_2.png \
    ../image/button/calendarBtn.png \
    ../image/button/calendarBtnChecked.png \
    ../image/button/calendarBtnChecked_2.png \
    ../image/button/calendarBtn_2.png \
    ../image/button/calendarNextBtn.png \
    ../image/button/calendarNextBtn_2.png \
    ../image/button/calendarPreviousBtn.png \
    ../image/button/calendarPreviousBtn_2.png \
    ../image/button/cameraControlClose.png \
    ../image/button/cameraControlCloseHover.png \
    ../image/button/cameraControlCloseHover_2.png \
    ../image/button/cameraControlClose_2.png \
    ../image/button/cameraControlOpen.png \
    ../image/button/cameraControlOpen_2.png \
    ../image/button/cardVideoFilePath.png \
    ../image/button/cardVideoFilePathHover.png \
    ../image/button/cardVideoFilePathHover_2.png \
    ../image/button/cardVideoFilePath_2.png \
    ../image/button/chevron-down.png \
    ../image/button/chevron-down_2.png \
    ../image/button/closeButton.png \
    ../image/button/closeButtonSmall.png \
    ../image/button/closeButtonSmall_2.png \
    ../image/button/closeButton_2.png \
    ../image/button/closeHoverBtn.png \
    ../image/button/closeHoverBtn_2.png \
    ../image/button/cloudBatchSelect.png \
    ../image/button/cloudBatchSelect_2.png \
    ../image/button/cloudBatchUnSelect.png \
    ../image/button/cloudBatchUnSelect_2.png \
    ../image/button/cloudChecked.png \
    ../image/button/cloudChecked_2.png \
    ../image/button/cloudUnChecked.png \
    ../image/button/cloudUnChecked_2.png \
    ../image/button/cloundRestoreButton.png \
    ../image/button/comboxExpand.png \
    ../image/button/comboxExpand_2.png \
    ../image/button/comboxSmall.png \
    ../image/button/comboxSmall_2.png \
    ../image/button/deleteBtn.png \
    ../image/button/deviceCheckedStatus.png \
    ../image/button/deviceCheckedStatus_2.png \
    ../image/button/deviceHoverStatus.png \
    ../image/button/deviceHoverStatus_2.png \
    ../image/button/deviceManagerHover.png \
    ../image/button/deviceManagerHover_2.png \
    ../image/button/deviceManagerNormal.png \
    ../image/button/deviceManagerNormal_2.png \
    ../image/button/deviceNormal.png \
    ../image/button/deviceNormal_2.png \
    ../image/button/download.png \
    ../image/button/download_2.png \
    ../image/button/download_transparency.png \
    ../image/button/download_transparency_2.png \
    ../image/button/export.png \
    ../image/button/export_2.png \
    ../image/button/fullScreen.png \
    ../image/button/fullScreen_2.png \
    ../image/button/hornIcon.png \
    ../image/button/hornIcon_2.png \
    ../image/button/inforChecked.png \
    ../image/button/inforChecked_2.png \
    ../image/button/inforHover.png \
    ../image/button/inforHover_2.png \
    ../image/button/inforNormal.png \
    ../image/button/inforNormal_2.png \
    ../image/button/intercomClose.png \
    ../image/button/intercomCloseHover.png \
    ../image/button/intercomCloseHover_2.png \
    ../image/button/intercomClose_2.png \
    ../image/button/intercomOpenStatus.png \
    ../image/button/intercomOpenStatus_2.png \
    ../image/button/localFileHover.png \
    ../image/button/localFileHover_2.png \
    ../image/button/localFileNormal.png \
    ../image/button/localFileNormal_2.png \
    ../image/button/meunCheckedStatus.png \
    ../image/button/meunCheckedStatus_2.png \
    ../image/button/next.png \
    ../image/button/nextPageDisableBtn.png \
    ../image/button/nextPageDisableBtn_2.png \
    ../image/button/nextPageHoverBtn.png \
    ../image/button/nextPageHoverBtn_2.png \
    ../image/button/nextPageNormalBtn.png \
    ../image/button/nextPageNormalBtn_2.png \
    ../image/button/next_disable.png \
    ../image/button/noMaximizedButton.png \
    ../image/button/noMaximizedButtonHover.png \
    ../image/button/noMaximizedButtonHover_2.png \
    ../image/button/noMaximizedButton_2.png \
    ../image/button/photoChecked.png \
    ../image/button/photoChecked_2.png \
    ../image/button/photoHover.png \
    ../image/button/photoHover_2.png \
    ../image/button/photoNormal.png \
    ../image/button/photoNormal_2.png \
    ../image/button/pictureRatio.png \
    ../image/button/pictureRatio_2.png \
    ../image/button/playButtonChecked.png \
    ../image/button/playButtonChecked_2.png \
    ../image/button/playButtonHover.png \
    ../image/button/playButtonHover_2.png \
    ../image/button/playButtonNormal.png \
    ../image/button/playButtonNormal_2.png \
    ../image/button/powerIcon.png \
    ../image/button/powerIcon_2.png \
    ../image/button/powerManagement.png \
    ../image/button/powerManagement_2.png \
    ../image/button/prePageDisableBtn.png \
    ../image/button/prePageDisableBtn_2.png \
    ../image/button/prePageHoverBtn.png \
    ../image/button/prePageHoverBtn_2.png \
    ../image/button/prePageNormalBtn.png \
    ../image/button/prePageNormalBtn_2.png \
    ../image/button/previous.png \
    ../image/button/previous_disable.png \
    ../image/button/realButtonChecked.png \
    ../image/button/realButtonChecked@2x.png \
    ../image/button/realButtonChecked_2.png \
    ../image/button/realButtonHover.png \
    ../image/button/realButtonHover_2.png \
    ../image/button/realButtonNormal.png \
    ../image/button/realButtonNormal_2.png \
    ../image/button/refreshButton.png \
    ../image/button/refreshButton_2.png \
    ../image/button/refreshHoverButton.png \
    ../image/button/refreshHoverButton_2.png \
    ../image/button/retryPressed.png \
    ../image/button/retryPressed_2.png \
    ../image/button/sdCardSelected.png \
    ../image/button/sdCardSelected_2.png \
    ../image/button/sdCardUnSelected.png \
    ../image/button/sdCardUnSelected_2.png \
    ../image/button/search.png \
    ../image/button/sliderBtnError.png \
    ../image/button/sliderBtnError_2.png \
    ../image/button/sliderBtnHover.png \
    ../image/button/sliderBtnHover_2.png \
    ../image/button/sliderBtnNormal.png \
    ../image/button/sliderBtnNormal_2.png \
    ../image/button/sliderCheckBox.png \
    ../image/button/sliderCheckBox_2.png \
    ../image/button/uploading.png \
    ../image/button/uploading_2.png \
    ../image/button/videoChecked.png \
    ../image/button/videoChecked_2.png \
    ../image/button/videoHover.png \
    ../image/button/videoHover_2.png \
    ../image/button/videoNormal.png \
    ../image/button/videoNormal_2.png \
    ../image/button/videoReplayChecked.png \
    ../image/button/videoReplayChecked_2.png \
    ../image/button/videoReplayHover.png \
    ../image/button/videoReplayHover_2.png \
    ../image/button/videoReplayNormal.png \
    ../image/button/videoReplayNormal_2.png \
    ../image/button/vipReviewButton.png \
    ../image/button/vipReviewButton_2.png \
    ../image/button/voiceCheceked.png \
    ../image/button/voiceCheceked_2.png \
    ../image/button/voiceClose.png \
    ../image/button/voiceCloseHover.png \
    ../image/button/voiceCloseHover_2.png \
    ../image/button/voiceClose_2.png \
    ../image/button/zoolSlider.png \
    ../image/button/zoolSlider_2x.png \
    ../image/button/zoolSlider_hover.png \
    ../image/button/zoolSlider_hover2x.png \
    ../image/button/zoolSlider_normal.png \
    ../image/button/zoolSlider_normal2x.png \
    ../image/button/zoom.png \
    ../image/button/zoom2x.png \
    ../image/button/zoomChecked.png \
    ../image/button/zoomClose.png \
    ../image/button/zoomCloseHover.png \
    ../image/button/zoom_hover.png \
    ../image/button/zoom_hover2x.png \
    ../image/button/zoom_normal.png \
    ../image/button/zoom_normal2x.png \
    ../image/edit/LXCheckBoxChecked.png \
    ../image/edit/LXCheckBoxChecked_2.png \
    ../image/edit/LXCheckBoxHover.png \
    ../image/edit/LXCheckBoxHover_2.png \
    ../image/edit/LXCheckBoxNormal.png \
    ../image/edit/LXCheckBoxNormal_2.png \
    ../image/edit/checkBoxChecked.png \
    ../image/edit/checkBoxChecked_2.png \
    ../image/edit/checkBoxHover.png \
    ../image/edit/checkBoxHover_2.png \
    ../image/edit/checkBoxNormal.png \
    ../image/edit/checkBoxNormal_2.png \
    ../image/edit/deviceStatus.png \
    ../image/edit/deviceStatus_2.png \
    ../image/edit/expanded.png \
    ../image/edit/expanded_2.png \
    ../image/edit/ptzDownControl.png \
    ../image/edit/ptzDownControl_2.png \
    ../image/edit/ptzLeftControl.png \
    ../image/edit/ptzLeftControl_2.png \
    ../image/edit/ptzRightControl.png \
    ../image/edit/ptzRightControl_2.png \
    ../image/edit/ptzUpControl.png \
    ../image/edit/ptzUpControl_2.png \
    ../image/edit/pztControl.png \
    ../image/edit/pztControl_2.png \
    ../image/edit/safeIcon.png \
    ../image/edit/safeIcon_2.png \
    ../image/edit/searchButton.png \
    ../image/edit/searchButton_2.png \
    ../image/edit/systole.png \
    ../image/edit/systole_2.png \
    ../image/general/Fairytale.png \
    ../image/general/Fairytale_2.png \
    ../image/general/LXDeviceSelected.png \
    ../image/general/LXDeviceSelected_2.png \
    ../image/general/LXTipsIcon.png \
    ../image/general/LXTipsIcon_2.png \
    ../image/general/LXdownLoadRecordHover.png \
    ../image/general/LXdownLoadRecordHover_2.png \
    ../image/general/LXsdCardRecordHover.png \
    ../image/general/LXsdCardRecordHover_2.png \
    ../image/general/MoveDownDepartment.png \
    ../image/general/MoveDownDepartment_2.png \
    ../image/general/MoveUpDepartment.png \
    ../image/general/MoveUpDepartment_2.png \
    ../image/general/addSubDepartment.png \
    ../image/general/addSubDepartment_2.png \
    ../image/general/basicInformation.png \
    ../image/general/basicInformationHover.png \
    ../image/general/basicInformationHover_2.png \
    ../image/general/basicInformation_2.png \
    ../image/general/bigLog.png \
    ../image/general/cardPlayClose.png \
    ../image/general/cardPlayClose_2.png \
    ../image/general/cardVideoEmptyTips.png \
    ../image/general/cardVideoEmptyTips_2.png \
    ../image/general/chargingBg.png \
    ../image/general/chargingState.png \
    ../image/general/chargingState_2.png \
    ../image/general/chevron-down@2x.png \
    ../image/general/chevron-up@2x.png \
    ../image/general/closeBtn.png \
    ../image/general/closeBtnHover.png \
    ../image/general/closeBtnHover_2.png \
    ../image/general/closeBtnRename.png \
    ../image/general/closeBtnRename_2.png \
    ../image/general/closeBtnWhite.png \
    ../image/general/closeBtnWhite_2.png \
    ../image/general/closeBtn_2.png \
    ../image/general/closeHover.png \
    ../image/general/closeHover_2.png \
    ../image/general/deleteDepartment.png \
    ../image/general/deleteDepartment_2.png \
    ../image/general/deleteIcon.png \
    ../image/general/deleteIcon_2.png \
    ../image/general/detectionAlarm.png \
    ../image/general/detectionAlarmHover.png \
    ../image/general/detectionAlarmHover_2.png \
    ../image/general/detectionAlarm_2.png \
    ../image/general/deviceOffLine.png \
    ../image/general/deviceOffLine_2.png \
    ../image/general/deviceOnline.png \
    ../image/general/deviceOnlineGreen.png \
    ../image/general/deviceOnlineGreen_2.png \
    ../image/general/deviceOnline_2.png \
    ../image/general/deviceSelected.png \
    ../image/general/deviceSelected_2.png \
    ../image/general/disconnect1.png \
    ../image/general/disconnect1_2.png \
    ../image/general/downLoadRecord.png \
    ../image/general/downLoadRecordHover.png \
    ../image/general/downLoadRecordHover_2.png \
    ../image/general/downLoadRecord_2.png \
    ../image/general/editDepartment.png \
    ../image/general/editDepartment_2.png \
    ../image/general/errorTips.png \
    ../image/general/errorTips_2.png \
    ../image/general/expandGray.png \
    ../image/general/expandGray_2.png \
    ../image/general/eyeClose.png \
    ../image/general/eyeClose_2.png \
    ../image/general/eyeOpen.png \
    ../image/general/eyeOpen_2.png \
    ../image/general/failTips.png \
    ../image/general/failTips_2.png \
    ../image/general/haveExpand.png \
    ../image/general/haveExpand_2.png \
    ../image/general/haveShrink.png \
    ../image/general/haveShrinkWhite.png \
    ../image/general/haveShrink_2.png \
    ../image/general/hibernationIcon.png \
    ../image/general/hibernationIcon_2.png \
    ../image/general/imageSetting.png \
    ../image/general/imageSettingHover.png \
    ../image/general/imageSettingHover_2.png \
    ../image/general/imageSetting_2.png \
    ../image/general/importDepartment.png \
    ../image/general/importDepartment_2.png \
    ../image/general/j3_fw1200.gif \
    ../image/general/logIcon.png \
    ../image/general/logIcon_2.png \
    ../image/general/loginPwdIcon.png \
    ../image/general/loginPwdIcon_2.png \
    ../image/general/loginTips.png \
    ../image/general/loginTips_2.png \
    ../image/general/networkInformation.png \
    ../image/general/networkInformationHover.png \
    ../image/general/networkInformationHover_2.png \
    ../image/general/networkInformation_2.png \
    ../image/general/owningGroup.png \
    ../image/general/pauseIcon.png \
    ../image/general/pauseIcon_2.png \
    ../image/general/progressIco.png \
    ../image/general/progressIco_2.png \
    ../image/general/reNameIcon.png \
    ../image/general/reNameIcon_2.png \
    ../image/general/replayIcon.png \
    ../image/general/replayIcon_2.png \
    ../image/general/resultError.png \
    ../image/general/resultError_2.png \
    ../image/general/resultOk.png \
    ../image/general/resultOk_2.png \
    ../image/general/sdCardRecord.png \
    ../image/general/sdCardRecordHover.png \
    ../image/general/sdCardRecordHover_2.png \
    ../image/general/sdCardRecord_2.png \
    ../image/general/selectIco.png \
    ../image/general/selectIco_2.png \
    ../image/general/settingIcon.png \
    ../image/general/settingIcon_2.png \
    ../image/general/sleepIcon.png \
    ../image/general/sleepIcon_2.png \
    ../image/general/systoleGray.png \
    ../image/general/systoleGray_2.png \
    ../image/general/tipsIcon.png \
    ../image/general/tipsIcon_2.png \
    ../image/general/videoCallAnswered.png \
    ../image/general/videoCallAnswered_2.png \
    ../image/general/videoCallMissed.png \
    ../image/general/videoCallMissed_2.png \
    ../image/general/welcomeFont.png \
    ../image/general/wifiNoPwdSignal1.png \
    ../image/general/wifiNoPwdSignal1_2.png \
    ../image/general/wifiNoPwdSignal2.png \
    ../image/general/wifiNoPwdSignal2_2.png \
    ../image/general/wifiNoPwdSignal3.png \
    ../image/general/wifiNoPwdSignal3_2.png \
    ../image/general/wifiNoPwdSignal4.png \
    ../image/general/wifiNoPwdSignal4_2.png \
    ../image/general/wifiNoPwdSignalGrey1.png \
    ../image/general/wifiNoPwdSignalGrey1_2.png \
    ../image/general/wifiNoPwdSignalGrey2.png \
    ../image/general/wifiNoPwdSignalGrey2_2.png \
    ../image/general/wifiNoPwdSignalGrey3.png \
    ../image/general/wifiNoPwdSignalGrey3_2.png \
    ../image/general/wifiNoPwdSignalGrey4.png \
    ../image/general/wifiNoPwdSignalGrey4_2.png \
    ../image/general/wifiSignal.png \
    ../image/general/wifiSignal1.png \
    ../image/general/wifiSignal1_2.png \
    ../image/general/wifiSignal2.png \
    ../image/general/wifiSignal2_2.png \
    ../image/general/wifiSignal3.png \
    ../image/general/wifiSignal3_2.png \
    ../image/general/wifiSignal4.png \
    ../image/general/wifiSignal4_2.png \
    ../image/general/wifiSignalGrey1.png \
    ../image/general/wifiSignalGrey1_2.png \
    ../image/general/wifiSignalGrey2.png \
    ../image/general/wifiSignalGrey2_2.png \
    ../image/general/wifiSignalGrey3.png \
    ../image/general/wifiSignalGrey3_2.png \
    ../image/general/wifiSignal_2.png \
    ../shader/fragment.fsh \
    ../shader/vertex.vsh \
    ../transltor/VmsTreanslator_EN.qm \
    ../transltor/VmsTreanslator_EN.ts \
    ../transltor/VmsTreanslator_EN11.qm \
    ../transltor/qt_en.qm \
    ../verify_code/index.html \
    ../verify_code/js/axios.min.js \
    ../verify_code/js/gt4.js \
    ../verify_code/js/qwebchannel.js \
    ../verify_code/js/vconsole.min.js \
    ../verify_code/js/vue.js \
    ../windowIcon.png \
    Gbk_convert_Utf8Bom.py \
    README.txt \
    VmsTranslator_EN.qm \
    convert_to_gbk.py \
    generateQmFile.bat \
    qt_en.qm \
    qt_zh_CN.qm \
    qtwebengine_zh_CN.qm \
    script.bat

RESOURCES += \
    ../../commonWidget/images.qrc \
    ../../commonWidget/images.qrc \
    ../Html.qrc \
    ../Html.qrc \
    ../LianXiangPageStyle.qrc \
    ../LianXiangPageStyle.qrc \
    ../QiaoAnPageStyle.qrc \
    ../QiaoAnPageStyle.qrc \
    ../image.qrc \
    ../image.qrc \
    ../page.qrc \
    ../page.qrc \
    ../translations.qrc

SUBDIRS += \
    ../transltor/VmsTranslate.pro
